### ISSUE TITLE
Add code pop-up behaves differently.

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#417] opened 2022-09-22 07:18 UTC
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Testing in staging after deprecation changes \(though not sure if related\).

* I create a new SL version of a published vocabulary.
* I click on ‘Add code’ without having clicked on any code in the table. The pop-up is OK.
* I click on ‘Add code’ after I have clicked on a parent code and it is blue. The pop-up is OK.
* I click on ‘Add code’ after I have click on a child code and it is blue. The pop-up shows the parent code \(here Code4\) of that child above the Code field.

![](https://bitbucket.org/repo/A6bqkay/images/740294460-image.png)
‌

When I add the new code and save it, the system puts it as the child of that parent \(Code4\). 

Previously the system put new codes as last if the user did not do anything. 

This might be a good change, making it easier to add new codes directly in right place but need to discuss with others what they think.

‌

**Comment by MajaDolinar** [comment] 2023-09-13 07:08
The issue is resolved, closing for now.

**Closed by MajaDolinar** 2023-09-13 07:08 UTC
Labels: major, task, user facing
