### ISSUE TITLE
Create a new superuser role

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#472] opened 2023-01-26 12:06 UTC
**Original report on BitBucket by Maja Dolinar.**

----------------------------------------

In order to distinguish between the roles ADMIN\_CONTENT and ROLE\_ADMIN, we need to create a new superuser role. ADMIN\_CONTENT should have content rights and user management rights in the system, whereas ROLE\_ADMIN should have all rights. Need to create a new table for this.

**Comment by MajaDolinar** [comment] 2023-03-22 13:13
See table: https://docs.google.com/spreadsheets/d/1wLKK0B5SrSsGsOO7PtZW3E7QPBuJUmwzRHV_WtljNSY/edit#gid=0 

currently the role ADMIN_CONTENT does not have user management rights in the system (I as a user in CVS need to have now 2 roles assigned: ROLE_ADMIN_CONTENT and ROLE_ADMIN to be able to manage users). In the future I should have only the ROLE_ADMIN_CONTENT

ROLE_ADMIN should have all rights. 

See previously closed issue for this https://github.com/cessda/cessda.cvs.two/issues/395: ROLE_ADMIN_CONTENT and ROLE_ADMIN were clashing, because they had the same rights in the system. For release 3.0.0 we will not include User management roles for ROLE_ADMIN_CONTENT, and have ROLE_ADMIN assigned to user that need user management.

**Comment by pakoselo** [comment] 2023-03-22 17:44
So I am little bit confused. The plan is to have only one role admin?

Martin

**Comment by MajaDolinar** [comment] 2023-03-22 19:31
I am not sure what other rights there are in the system that are connected to maintenance, if any. Maybe @john-shepherdson or @Joshua-cessda-admin can help in this? I think that only the rights of accessing some technical part of the service would separate ROLE_ADMIN_CONTENT and ROLE_ADMIN probably.

**Comment by pakoselo** [comment] 2023-03-22 21:00
That make sense to me. If this is the correct approach I can implement it
like that.

**Comment by john-shepherdson** [comment] 2023-03-23 09:24
Nothing to add

**Comment by pakoselo** [comment] 2023-03-27 07:15
@MajaDolinar the roles should be solved. I also solve the problems with TECHNICAL_ADMIN (nobody noticed, that it probably doesn't work). @Joshocan @john-shepherdson I need also to modify the application.yml, where the health section can be accessed only by ADMIN, not TECHNICAL_ADMIN. I don't know, if there are other configurations on the production, but to be sure, the roles are right also on the production. @MajaDolinar I have merged the code with the master, so in few minutes/hours it should be on dev and/or staging and you shpould be able to test it. If not, @Joshocan please check the deployment as it breaks sometimes. Thanks

**Closed** 2023-04-26 08:43 UTC
Labels: bug, major, user facing, resolved

**Comment by MajaDolinar** [comment] 2023-04-26 11:17
needs testing

**Comment by MajaDolinar** [comment] 2023-05-03 14:04
ROLE_ADMIN_CONTENT is working for user management as well. The issue is resolved.
