### ISSUE TITLE
Latest vs previous version distinction for users

### ISSUE THREAD

**Issue by MajaDolinar** [cessda/cessda.cvs.two#581] opened 2023-03-22 07:04 UTC
A vocabulary shows all languages even though the latest version may not include all languages (some languages might be on previous version - user sees the version only when they click on the language in the table view) - this should be graphically visible to the user. Proposal: grey out the languages that are not included in the latest version + when clicked on the language, put the Version number in orange colour (in this case the user would have the information what languages are included in the latest version and which languages for the CV are also available but are on some previous version). 

![image](https://user-images.githubusercontent.com/72601736/226825927-364a9199-79fb-452c-b512-a2d47a200eaa.png)

![image](https://user-images.githubusercontent.com/72601736/226826126-098e6a94-09d8-4f9e-aa36-b34bc4e6112d.png)

Vocabulary view: showing all languages even though the latest version may not include all languages. Proposal: grey out the languages that are not included in the latest version + when clicked on the language, put the Version number in orange colour 
![image](https://user-images.githubusercontent.com/72601736/226826260-c6b704d9-d81f-480f-8096-75810d65bfa6.png)

![image](https://user-images.githubusercontent.com/72601736/226826384-2571e9eb-d29b-4f38-bece-251c2bd8c3f3.png)

**Comment by MajaDolinar** [comment] 2023-03-22 12:18
+ maybe show the version number when hovering the language with a mouse -- in table view

**Comment by Stifo** [comment] 2023-04-28 10:54
@MajaDolinar 
i've done some adjustments to this issue in #624. it's already merged with the main branch but i can't tell when you can test it in dev/staging.

i had to change your requests slightly due to a funcionality that was already there. please, let me explain the functionality and what i have done to the visualization (i did not alter the functionality).

Publication vocabulary details screen:
the functionality is that the content of the screen changes with the selected version (a click on a language button and  choosing a version from the dropdown list). i've changed the visualization to follow this logic, so that versions, which do not fall in the currently selected bundle are filled gray.
I've changed the version number showing in the vocabulary details screen at the top (e.g.: CVs Editor search › TopicClassification v.4.2.3) to follow currently selected version.

Editor vocabulary details screen:
the functionality is similar to Publication, but there's not dropdown list of versions for languages. there are just the latest versions showing for each language. i've changed the visualization the same way as in the Publication vocabulary details screen - versions, which do not fall in the currently selected bundle are filled gray.
I've changed the version number showing in the vocabulary details screen at the top (e.g.: CVs Editor search › TopicClassification v.4.2.3) to follow currently selected version.

Home screen:
the functionality is to show the most recent versions per search result and user can click on language, which leads to a notation, description and version change in the result display. however, there's no logic in the code to track the currently selected language as it is in the Editor/Publication vocabulary details screens. so i just gray out versions, which are not in the latest bundle. if user clicks on the language button of a version outside the bundle, that button is set to orange.

Editor screen:
similar to Home screen.

**Comment by MajaDolinar** [comment] 2023-05-03 13:41
I tested on staging and it looks great. I think it is now understandable to users what it means and what is included in each of the versions. 

@Stifo what does it mean if the button is orange? I do not quite understand this orange now.
![Screenshot 2023-05-03 at 15 40 33](https://user-images.githubusercontent.com/72601736/235933325-78f18244-283f-4509-aaab-1242e418eb65.png)

**Comment by Stifo** [comment] 2023-05-03 15:23
@MajaDolinar
the problem is most probably related to #607 - the SQL script were not successfully executed OR there is an SQL cache with old data still active. @Joshocan, please, check the SQL script execution and DB caches. 

I've tested this issue locally and reproduced the same behavior with the orange color 'EN' when the #607 scripts were not  successfully executed.

**Comment by MajaDolinar** [comment] 2023-05-09 07:10
I still see one orange button for GESIS [Elective Studies category scheme (KategorienschemaWahlstudien)](https://vocabularies-staging.cessda.eu/vocabulary/KategorienschemaWahlstudien?lang=en)
Please have a look.

The software package one from before is now ok.

**Closed** 2023-05-09 13:41 UTC
Labels: user facing

**Comment by MajaDolinar** [comment] 2023-05-09 14:08
Looks good, ready for release on production.
